[package]
name = "xrpl-library"
version = "0.1.0"
edition = "2021"

[dependencies]
xrpl = "0.1.2"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4"